spring:
  application:
    name: payment-service

  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # ? Add this

server:
  port: 5006

razorpay:
  api:
    key: ${RAZORPAY_API_KEY}
    secret: ${RAZORPAY_SECRET}

stripe:
  api:
    key: "your stripe api key"

eureka:
  instance:
    prefer-ip-address: true

  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: "http://localhost:8070/eureka/"